CREATE TABLE [dbo].[CLIENTE]
(
	[IDCLIENTE]             INT IDENTITY(1,1) NOT NULL , 
    [IDENTIFICACIONCLIENTE] VARCHAR(10)     NULL, 
    [NOMBRECLIENTE]         VARCHAR(100)    NULL, 
    [DIRECCIONCLIENTE]      VARCHAR(200)    NULL, 
    [CELULARCLIENTE]        VARCHAR(10)     NULL, 
    [CORREOCLIENTE]         VARCHAR(100)    NULL, 
    [ASESOR]                INT             NULL, 
    [ESTADOCLIENTE]         BIT             NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY (IDCLIENTE)
)
