CREATE TABLE [dbo].[DIRECCION]
(
	[IDDIRECCION]       INT IDENTITY(1, 1) NOT NULL, 
    [IDPROVINCIA]       INT NULL, 
    [IDCANTON]          INT NULL, 
    [IDPARROQUIA]       INT NULL, 
    [IDBARRIO]          INT NULL, 
    [CALLEPRINCIPAL]    VARCHAR(100) NULL, 
    [NUMERACION]        VARCHAR(25) NULL, 
    [CALLESECUNDARIA]   VARCHAR(50) NULL, 
    [IDPROPIEDAD]       INT NULL, 
    [ESTADO]            BIT NULL,
    CONSTRAINT [PK_DIRECCION] PRIMARY KEY (IDDIRECCION)
)
