CREATE TABLE [dbo].[IMAGEN]
(
	[IDIMAGEN]      INT             NOT NULL , 
    [IDPROPIEDAD]   INT             NULL, 
    [PATH]          VARCHAR(100)    NULL, 
    [ESTADOIMAGEN]  INT             NULL,
    CONSTRAINT [PK_IMAGEN] PRIMARY KEY (IDIMAGEN),
    CONSTRAINT [PROPIEDAD_IMAGEN_FK] FOREIGN KEY (IDPROPIEDAD) REFERENCES PROPIEDAD(IDPROPIEDAD)
)
