CREATE TABLE [dbo].[PARROQUIA]
(
	[IDPARROQUIA]       INT IDENTITY(1,1) NOT NULL, 
    [IDCANTON]          INT             NULL, 
    [CODPARROQUIA]      VARCHAR(6)      NULL, 
    [NOMBREPARROQUIA]   VARCHAR(100)    NULL, 
    [ESTADOPARROQUIA]   BIT             NULL,
    CONSTRAINT [PK_PARROQUIA] PRIMARY KEY (IDPARROQUIA),
    CONSTRAINT [CANTON_PARROQUIA_FK] FOREIGN KEY (IDCANTON) REFERENCES CANTON(IDCANTON)
)
