CREATE TABLE [dbo].[PROPIEDAD]
(
	[IDPROPIEDAD]               INT IDENTITY(1, 1) NOT NULL , 
    [IDCARACTERISTICA]          INT             NULL, 
    [IDPROVINCIA]               INT             NULL, 
    [IDTIPOPROPIEDAD]           INT             NULL, 
    [IDPROPIETARIO]             INT             NULL, 
    [IDUSUARIO]                 INT             NULL, 
    [PRECIO]                    DECIMAL         NULL, 
    [FECHAREGISTROPROPIEDAD]    DATETIME        NULL, 
    [FOTOPRINCIPAL]             VARCHAR(200)    NULL, 
    [ESTADOPROPIEDAD]           BIT             NULL,
    CONSTRAINT [PK_PROPIEDAD] PRIMARY KEY (IDPROPIEDAD),
    CONSTRAINT [CARACTERISTICA_PROPIEDAD_FK] FOREIGN KEY (IDCARACTERISTICA) REFERENCES CARACTERISTICA(IDCARACTERISTICA),
    CONSTRAINT [PROPIETARIO_PROPIEDAD_FK] FOREIGN KEY (IDPROPIETARIO) REFERENCES PROPIETARIO(IDPROPIETARIO),
    CONSTRAINT [PROVINCIA_PROPIEDAD_FK] FOREIGN KEY ([IDPROVINCIA]) REFERENCES PROVINCIA(IDPROVINCIA),
    CONSTRAINT [TIPOPROPIEDAD_PROPIEDAD_FK] FOREIGN KEY (IDTIPOPROPIEDAD) REFERENCES TIPO_PROPIEDAD(IDTIPOPROPIEDAD),
    CONSTRAINT [USUARIO_PROPIEDAD_FK] FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
)
