CREATE TABLE [dbo].[PROPIETARIO]
(
	[IDPROPIETARIO]         INT             NOT NULL , 
    [NOMBREPROPIETARIO]     VARCHAR(100)    NULL, 
    [DIRECCIONPROPIETARIO]  VARCHAR(200)    NULL, 
    [CELULARPROPIETARIO]    VARCHAR(10)     NULL, 
    [CORRREOPROPIETARIO]    VARCHAR(100)    NULL, 
    [ESTADOPROPIETARIO]     BIT             NULL,
    CONSTRAINT [PK_PROPIETARIO] PRIMARY KEY (IDPROPIETARIO)
)
