CREATE TABLE [dbo].[TIPO_PROPIEDAD]
(
	[IDTIPOPROPIEDAD]       INT IDENTITY(1, 1) NOT NULL , 
    [NOMBRETIPOPROPIEDAD]   VARCHAR(50) NULL, 
    [ESTADOTIPOPROPIEDAD]   BIT         NULL,
    CONSTRAINT [PK_TIPO_PROPIEDAD] PRIMARY KEY (IDTIPOPROPIEDAD)
)
