CREATE PROCEDURE [dbo].[ConsultarParroquias]
	@i_id_canton int = null
AS

SELECT	PARROQUIA.*,
		CANTON.NOMBRECANTON
FROM	PARROQUIA
		JOIN CANTON ON PARROQUIA.IDCANTON = CANTON.IDCANTON
WHERE	PARROQUIA.IDCANTON = ISNULL(@i_id_canton, PARROQUIA.IDCANTON)
ORDER BY PARROQUIA.IDPARROQUIA

RETURN 0
