CREATE PROCEDURE [dbo].[ConsultarBarrios]
	@i_id_parroquia int = null
AS

SELECT	BARRIO.*,
		PARROQUIA.NOMBREPARROQUIA
FROM	BARRIO
		JOIN PARROQUIA ON BARRIO.IDPARROQUIA = PARROQUIA.IDPARROQUIA
WHERE	BARRIO.IDPARROQUIA = ISNULL(@i_id_parroquia, BARRIO.IDPARROQUIA)
ORDER BY BARRIO.IDBARRIO

RETURN 0