CREATE PROCEDURE [dbo].[ConsultarTransaccionesUsuario]
	@i_nombre_usuario		varchar(30)
AS

SELECT	TRANSACCION.*
FROM	USUARIO
		JOIN ROL ON USUARIO.IDROL = ROL.IDROL
		JOIN TRANSACCIONROL ON ROL.IDROL = TRANSACCIONROL.IDROL
		JOIN TRANSACCION ON TRANSACCIONROL.IDTRANSACCION = TRANSACCION.IDTRANSACCION
WHERE	USUARIO.USERNAME = @i_nombre_usuario
AND		TRANSACCION.ESTADO = 1
AND		TRANSACCION.SUBMENU = 0
ORDER BY TRANSACCION.IDTRANSACCION

RETURN 0
