CREATE PROCEDURE [dbo].[ConsultarTransaccionesRolSeguridad]
	@i_id_rol_seguridad		int
AS

SELECT	TRANSACCION.*,
		TRANSACCIONROL.IDTRANSACCIONROL
FROM	TRANSACCIONROL
		JOIN TRANSACCION ON TRANSACCIONROL.IDTRANSACCION = TRANSACCION.IDTRANSACCION
WHERE	TRANSACCIONROL.IDROL = @i_id_rol_seguridad
  AND	TRANSACCION.ESTADO = 1
ORDER BY TRANSACCION.IDTRANSACCION

RETURN 0