CREATE PROCEDURE [dbo].[ConsultarCantones]
	@i_id_provincia INT = NULL
AS

SELECT	CANTON.*,
		PROVINCIA.NOMBREPROVINCIA
FROM	CANTON
		JOIN PROVINCIA ON CANTON.IDPROVINCIA = PROVINCIA.IDPROVINCIA
WHERE	CANTON.IDPROVINCIA = ISNULL(@i_id_provincia, CANTON.IDPROVINCIA)
ORDER BY CANTON.IDCANTON

RETURN 0
